apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centralidp-pen
spec:
  destination:
    namespace: product-portal-pen
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/centralidp
    repoURL: 'https://github.com/catenax-ng/tx-portal-iam.git'
    targetRevision: helm-environments
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f values-pen.yaml'
  project: project-portal
