apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: centralidp-keycloak
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.auth.existingSecret.adminpassword | default ( randAlphaNum 32 | quote ) }}
  management-password: {{ .Values.secrets.auth.existingSecret.managementpassword | default ( randAlphaNum 32 | quote ) }}
