{{- if not .Values.keycloak.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.externalDatabase.existingSecret}}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.keycloak.externalDatabase.password | default ( randAlphaNum 32 | quote ) }}
{{- end -}}
