{{- if .Values.secrets.realmuser.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-sharedidp-realms
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CX-Test-Access-users-0.json: {{ .Values.secrets.realmuser.cxtestaccessuser }}
  Company-1-users-0.json: {{ .Values.secrets.realmuser.company1user }}
  Company-2-users-0.json: {{ .Values.secrets.realmuser.company2user }}
  Security-Company-users-0.json: {{ .Values.secrets.realmuser.securitycompany }}
  CX-Operator-users-0.json: {{ .Values.secrets.realmuser.cxoperator }}
  Service-Provider-users-0.json: {{ .Values.secrets.realmuser.serviceprovider }}
  App-Provider-users-0.json: {{ .Values.secrets.realmuser.appprovider }}
{{- end -}}