apiVersion: v1
kind: Secret
metadata:
  name: sharedidp-postgres
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresql.auth.existingSecret.postgrespassword | default ( randAlphaNum 32 | quote ) }}
  password: {{ .Values.secrets.postgresql.auth.existingSecret.password | default ( randAlphaNum 32 | quote ) }}
  replication-password: {{ .Values.secrets.postgresql.auth.existingSecret.replicationPassword | default ( randAlphaNum 32 | quote ) }}